#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo "Tests started at…"
date "+%H:%M:%S"

# run tests
echo "Running tests…"
date "+%H:%M:%S"

script/test

 # If rspec & rubocop fail with exit status != 0 -> ci fails
echo $exitStatus
if [ $exitStatus -ne 0 ]; then
  echo "Some errors ocurred"
else
  echo "Success ✨"
fi
exit $exitStatus
