#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up ENV..."
if [ ! -f .env ]; then
  echo "Copying .env.template into .env..."
  cp .env.template .env
fi

echo "==> Setting up DB…"
# reset database to a fresh state.
bundle exec rake db:create
bundle exec rake db:reset

echo "==> Hacktoberfest is now ready to go!"
