#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# boot redis and sidekiq
redis-server
bundle exec sidekiq