name: Brakeman checks

on: [pull_request]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Checking vulnerabilities with Brakeman
      run: |
        gem install bundler bundle-only
        bundle-only lint
        brakeman --color
